### PR TITLE
Fixes failing xml-converter tests

### LINKED ISSUE #331: Failing xml-converter tests
As mentioned in #330, there are 5 failing xml-converter tests. It looks like there's something wrong with the paths for the `attrs.json` and `views.json` files.

### PR DESCRIPTION
**Pull request by kengorab**
This fixes #331. There were 5 failing xml-converter tests, due to an invalid path to the attrs.json and views.json files.

### CODE REVIEW

File: anko/idea-plugin/xml-converter/src/org/jetbrains/kotlin/android/xmlconverter/Util.kt [hunk 1]
```diff
@@ -23,9 +23,9 @@ import org.jetbrains.kotlin.android.attrs.readResource
 
 private val INTENT = "    "
 
-internal val attrs = Gson().fromJson(readResource("attrs.json"), Attrs::class.java)
+internal val attrs = Gson().fromJson(readResource("../attrs.json"), Attrs::class.java)
```
Comment (kengorab) [inline anko/idea-plugin/xml-converter/src/org/jetbrains/kotlin/android/xmlconverter/Util.kt]: I'm not too familiar with how java's `File` class determines its abstract pathname, but this was trying to read the resource at `/code/github/anko/anko/idea-plugin/xml-converter/attrs.json`, when it should be `/code/github/anko/anko/idea-plugin/attrs.json` (and likewise for `views.json`). I'm not sure if the abstract pathname is only set to `/code/github/anko/anko/idea-plugin/xml-converter` during the tests, but I'm not sure how this was working in production in the past.

File: anko/idea-plugin/xml-converter/test/org/jetbrains/kotlin/android/xmlconverter/BaseXmlConverterTest.java [hunk 2]
```diff
@@ -1,22 +1,23 @@
...
-import static org.junit.Assert.assertTrue;
 
 public class BaseXmlConverterTest {
 
     @Rule
     public TestName name = new TestName();
 
     protected void doLayoutTest() {
-        File testDataDir = new File("xml-converter/testData");
+        File testDataDir = new File("testData");
```
Comment (kengorab) [inline anko/idea-plugin/xml-converter/test/org/jetbrains/kotlin/android/xmlconverter/BaseXmlConverterTest.java]: See my comment above; the test was failing because the abstract pathname was set incorrectly. This was looking at `/code/github/anko/anko/idea-plugin/xml-converter/xml-converter/testData`, when it should be `/code/github/anko/anko/idea-plugin/xml-converter/testData`. 

Again, if I'm incorrect with these path changes, please let me know, because I'm not too certain how the abstract pathname gets set.

**Comment by yanex** [comment]
Thank you for the contribution!
